# Generated by Django 3.0.8 on 2020-10-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Essential_Glams', '0002_auto_20201008_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail_subscriber',
            name='Email_Subscribers',
            field=models.EmailField(max_length=400, unique=True),
        ),
    ]
