# Generated by Django 3.0.8 on 2020-10-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Essential_Glams', '0003_auto_20201008_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=1000)),
                ('User_Email', models.EmailField(max_length=1000)),
                ('Comment', models.CharField(max_length=1000000)),
            ],
        ),
    ]
