# Generated by Django 3.0.8 on 2020-10-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Essential_Glams', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
    ]
