# Generated by Django 3.0.8 on 2020-10-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Essential_Glams', '0007_auto_20201009_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
