# Generated by Django 3.0.8 on 2020-10-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Essential_Glams', '0008_auto_20201009_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
